---
title: "Academic and Professional Experiences"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Education

**Emory University**<br>                   
*Bachelor of Science in Applied Math and Statistics,* 2019-2023

**Columbia University**<br>
*Master in Public Health,* 2023-2025


# Internships

**FiberHome Telecommunication Technologies Co., Ltd.**<br>
*Data Analyst Intern*<br>
* Built a model to analyze and predict the churn of telecommunication subscribers and proposed suggestions for enhancing customer loyalty and reducing churn.<br>
* Participated in and completed several projects during the intern training program:<br>
	-Utilized K-means clustering to map Uniqlo store locations and segment their customer base.<br>


**Guotai Junan Securities Co., Ltd**<br>
*Data Analyst Intern*<br>
* Assisted in financial purchasing decisions by conducting market trend analyses using stock data.<br>
* Utilized Python to extract data via APIs, crafted visualizations using Plotly, and presented comprehensive reports detailing findings.<br>


**Research Experiences**
Quantitative Valuation in Financial Capital Markets	<br>
Advised by Prof. David Shimko, NYU ( Python/R )<br>
*Conducted a comprehensive analysis of the market valuation for companies like Zoom and Peloton during the Covid-19 outbreak, utilizing the Black Scholes and Monte-Carlo methods. <br>

*Performed data preprocessing, wrangling, and analysis of stock price and financial data leveraging Python and R.<br>


# Skills

Programming: Python, SQL, R, SAS, MATLAB<br>

Please also refer to the entire CV from here: [CV.pdf](CV.pdf)