---
title: "plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("ny_noaa")

#this code chunk is adpoted from lecture notes 
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything()) 
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A: Scatter Plot Showing tmin and tmax Across Locations

```{r}
weather_df|>
  mutate(text_label = str_c("name:", name, "\ntmin:", tmin, "\ntmax:", tmax))|>
  plot_ly(
    x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
    color = ~name, text = ~text_label, alpha = 0.5
  )

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
weather_df|>
  mutate(name = fct_reorder(name, tmax))|>
  plot_ly(y = ~tmax, color = ~name, type = "box", colors = "viridis")
```


### Chart C

```{r}
density = ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")
ggplotly(density)
```

